# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy \
            --remote-only \
            --access-token=${{ secrets.FLY_API_TOKEN }} \
            --env VITE_CV_LINK=${{ secrets.VITE_CV_LINK }} \
            --env VITE_GITHUB=${{ secrets.VITE_GITHUB }} \
            --env VITE_LINKEDIN=${{ secrets.VITE_LINKEDIN }} \
            --env VITE_MY_EMAIL=${{ secrets.VITE_MY_EMAIL }}
